asset/urls.py
from django.urls import path
from asset import views
from asset import api

urlpatterns = [
    path('asset.html', views.AssetListAll.as_view(), name='asset_list'),
    path('asset-add.html', views.AssetAdd.as_view(), name='asset_add'),
    path('asset-all-del.html', views.AssetAllDel.as_view(), name='asset_all_del'),
    path('asset-detail-<int:pk>.html', views.AssetDetail.as_view(), name='asset_detail'),
    path('asset-update-<int:pk>.html', views.AssetUpdate.as_view(), name='asset_update'),

    path('asset-ztree.html', views.AssetZtree, name='asset_ztree'),

    path('api/asset.html', api.AssetList.as_view(), name='asset_api_list'),
    path('api/asset-detail-<int:pk>.html', api.AssetDetail.as_view(), name='asset_api_detail'),

    path('asset-user.html', views.AssetUserListAll.as_view(), name='asset_user_list'),
    path('asset-user-add.html', views.AssetUserAdd.as_view(), name='asset_user_add'),
    path('asset-user-all-del.html', views.AssetUserAllDel.as_view(), name='asset_user_all_del'),
    path('asset-user-detail-<int:pk>.html', views.AssetUserDetail.as_view(), name='asset_user_detail'),
    path('asset-user-update-<int:pk>.html', views.AssetUserUpdate.as_view(), name='asset_user_update'),

    path('asset-user-asset-<int:pk>.html', views.AssetUserAsset, name='asset_user_asset'),

    path('asset-webssh.html', views.AssetWeb.as_view(), name='asset_web'),
    path('asset-hardware-update.html', views.AssetHardwareUpdate.as_view(), name='asset_hardware_update'),
]

app_name = "asset"

chain/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from index.views import index, login_view, logout, password_update, login_historys

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('', index),
    path('index', index, name="index"),
    path('login', login_view),
    path('logout', logout),
    path('password_update', password_update, name="password_update"),
    path('index/login-history', login_historys, name="login-history"),
    path('asset/', include('asset.urls', namespace="asset", ), ),
    # path('tasks/', include('tasks.urls', namespace="tasks", ), ),
]

asset/models.py
from django.db import models
import random

__all__ = [
    'AssetInfo',
    'AssetLoginUser',
]

# 登录用户
class AssetLoginUser(models.Model):
    hostname = models.CharField(max_length=64, verbose_name='名称', unique=True)
    username = models.CharField(
        max_length=64,
        verbose_name="用户名",
        default='root',
        null=True,
        blank=True)
    password = models.CharField(
        max_length=256,
        blank=True,
        null=True,
        verbose_name='密码')
    private_key = models.FileField(upload_to='upload/privatekey/%Y%m%d{}'.format(
        random.randint(0, 99999)), verbose_name="私钥", null=True, blank=True)

    ps = models.CharField(
        max_length=10240,
        verbose_name="备注",
        null=True,
        blank=True)
    ctime = models.DateTimeField(
        auto_now_add=True,
        null=True,
        verbose_name='创建时间',
        blank=True)
    utime = models.DateTimeField(
        auto_now=True,
        null=True,
        verbose_name='更新时间',
        blank=True)

    class Meta:
        db_table = "AssetLoginUser"
        verbose_name = "资产用户"
        verbose_name_plural = '资产用户'
        # permissions = {
        #     ('read_asset_user', u"只读资产用户"),
        # }

    def __str__(self):
        return self.hostname


class AssetInfo(models.Model):
    PLATFORM_CHOICES = (
        ("阿里云", "阿里云"),
        ("AWS", "AWS"),
        ("其他", "其他"),
    )
    REGION_CHOICES = (
        ("香港", '香港'),
        ("东京", '东京'),
    )

    MANAGER_CHOICES = (
        ('葛卢菁', 'glj'),
        ('其他', '其他'),
    )
    PROJECT_CHOICES = (
        ('项目1', '项目1'),
        ('项目2', '项目2'),
        ('项目3', '项目3'),
        ('其他', '其他')
    )
    # id = models.AutoField(primary_key=True, verbose_name="id")
    hostname = models.CharField(max_length=64, verbose_name='主机名', unique=True)
    network_ip = models.GenericIPAddressField(
        verbose_name='外网IP', unique=True, null=True, blank=True)
    inner_ip = models.GenericIPAddressField(
        verbose_name='内网IP', null=True, blank=True)

    system = models.CharField(
        max_length=128,
        verbose_name='系统版本',
        null=True,
        blank=True)
    cpu = models.CharField(
        max_length=64,
        verbose_name='CPU',
        null=True,
        blank=True)
    memory = models.CharField(
        max_length=64,
        verbose_name='内存',
        null=True,
        blank=True)
    disk = models.CharField(
        max_length=256,
        verbose_name="硬盘",
        null=True,
        blank=True)
    bandwidth = models.IntegerField(
        verbose_name='外网带宽',
        null=True,
        blank=True,
        default="1")

    platform = models.CharField(
        max_length=128,
        choices=PLATFORM_CHOICES,
        verbose_name='平台')
    region = models.CharField(
        max_length=128,
        choices=REGION_CHOICES,
        verbose_name='区域')

    manager = models.CharField(
        max_length=128,
        choices=MANAGER_CHOICES,
        verbose_name='负责人')
    project = models.CharField(
        max_length=128,
        choices=PROJECT_CHOICES,
        verbose_name='项目')

    user = models.ForeignKey(
        verbose_name="登录用户",
        to='AssetLoginUser',
        on_delete=models.SET_NULL,
        null=True,
        blank=True)

    Instance_id = models.CharField(
        max_length=64,
        verbose_name='实例ID',
        null=True,
        blank=True)

    buy_time = models.DateTimeField(verbose_name='购买时间', null=True, blank=True)
    expire_time = models.DateTimeField(
        verbose_name='到期时间', null=True, blank=True)

    ps = models.CharField(
        max_length=1024,
        verbose_name="备注",
        null=True,
        blank=True)
    port = models.IntegerField(
        verbose_name="登录端口",
        default='22',
        null=True,
        blank=True)
    is_active = models.BooleanField(default=True, verbose_name='激活')

    ctime = models.DateTimeField(
        auto_now_add=True,
        null=True,
        verbose_name='创建时间',
        blank=True)
    utime = models.DateTimeField(
        auto_now=True,
        null=True,
        verbose_name='更新时间',
        blank=True)

    @property
    def users(self):
        users = AssetLoginUser.objects.get(hostname=self.user)
        return users

    class Meta:
        db_table = "AssetInfo"
        verbose_name = "资产管理"
        verbose_name_plural = '资产管理'
        permissions = {
            ('read_asset', u"只读资产管理"),
        }

    def __str__(self):
        return self.hostname

asset/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.contrib.auth.decorators import login_required
from .form import  AssetForm, AssetUserForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import TemplateView, ListView, View, CreateView, UpdateView, DetailView
from django.urls import reverse_lazy
from django.conf import settings
from django.db.models import Q
from asset.models import AssetInfo, AssetLoginUser
from chain import settings
from index.password_crypt import encrypt_p, decrypt_p
from os import system
import json
import logging


logger = logging.getLogger('asset')



class AssetListAll(LoginRequiredMixin, ListView):
    """资产列表"""
    template_name = 'asset/asset.html'
    paginate_by = settings.DISPLAY_PER_PAGE
    model = AssetInfo
    context_object_name = "asset_list"
    queryset = AssetInfo.objects.all()
    ordering = ('id',)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_data = self.request.GET.copy()
        try:
            search_data.pop("page")
        except BaseException as e:
            logger.error(e)

        context.update(search_data.dict())
        context = {
            "asset_active": "active",
            "asset_list_active": "active",
            "search_data": search_data.urlencode(),
            "web_ssh": getattr(settings, 'web_ssh'),
            "web_port": getattr(settings, 'web_port'),
        }
        kwargs.update(context)

        return super().get_context_data(**kwargs)

    def get_queryset(self):
        """
         资产查询功能
        :return:
        """
        self.queryset = super().get_queryset()
        if self.request.GET.get('name'):
            query = self.request.GET.get('name', None)
            queryset = self.queryset.filter(Q(network_ip=query) | Q(hostname=query) | Q(
                inner_ip=query) | Q(project=query) | Q(manager=query)).order_by('-id')
        else:
            queryset = super().get_queryset()
        return queryset


class AssetAdd(LoginRequiredMixin, CreateView):
    """资产增加"""
    model = AssetInfo
    form_class = AssetForm
    template_name = 'asset/asset-add-update.html'
    success_url = reverse_lazy('asset:asset_list')

    def get_context_data(self, **kwargs):
        context = {
            "asset_active": "active",
            "asset_list_active": "active",
        }

        try:
            context['i__next__'] = self.request.META['HTTP_REFERER']
        except Exception as e:
            logger.error(e)
        kwargs.update(context)

        return super().get_context_data(**kwargs)



class AssetUpdate(LoginRequiredMixin, UpdateView):
    """资产更新"""

    model = AssetInfo
    form_class = AssetForm
    template_name = 'asset/asset-add-update.html'
    success_url = reverse_lazy('asset:asset_list')
    def get_context_data(self, **kwargs):

        context = {
            "asset_active": "active",
            "asset_list_active": "active",
        }


        try:
            context['i__next__'] = self.request.META['HTTP_REFERER']
        except Exception as e:
            logger.error(e)

        kwargs.update(context)
        print(context)
        print(super().get_context_data(**kwargs))

        return super().get_context_data(**kwargs)

    def get_success_url(self):
        self.url = self.request.POST['__next__']
        print('111111111111111',self.request.POST)
        return self.url


class AssetDetail(LoginRequiredMixin, DetailView):
    """
     资产详细
    """
    model = AssetInfo
    form_class = AssetForm
    template_name = 'asset/asset-detail.html'

    def get_context_data(self, **kwargs):
        pk = self.kwargs.get(self.pk_url_kwarg, None)
        detail = AssetInfo.objects.get(id=pk)
        # varall = Variable.objects.filter(assets=pk).values()
        context = {
            "asset_active": "active",
            "asset_list_active": "active",
            "assets": detail,
            "nid": pk,
            # "vars": varall,

        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)


class AssetAllDel(LoginRequiredMixin, View):
    """
    资产删除
    """
    model = AssetInfo

    @staticmethod
    def post(request):
        ret = {'status': True, 'error': None, }
        try:
            if request.POST.get('nid'):
                ids = request.POST.get('nid', None)
                AssetInfo.objects.get(id=ids).delete()
            else:
                ids = request.POST.getlist('id', None)
                idstring = ','.join(ids)
                AssetInfo.objects.extra(
                    where=['id IN (' + idstring + ')']).delete()
        except Exception as e:
            ret['status'] = False
            ret['error'] = '删除请求错误,没有权限{}'.format(e)
        finally:
            return HttpResponse(json.dumps(ret))


class AssetHardwareUpdate(LoginRequiredMixin, View):
    """
    资产硬件 异步更新
    """
    model = AssetInfo

    @staticmethod
    def post(request):
        ret = {'status': True, 'error': None, }
        try:
            if request.POST.get('nid'):
                ids = request.POST.get('nid', None)
                asset_obj = AssetInfo.objects.get(id=ids)
                try:
                    asset_obj.user.hostname
                except Exception as e:
                    logger.error(e)
                    ret['status'] = False
                    ret['error'] = '未关联用户，请关联后再更新'.format(e)
                    return HttpResponse(json.dumps(ret))

                assets = [{"hostname": asset_obj.hostname,
                           "ip": asset_obj.network_ip,
                           "port": asset_obj.port,
                           "username": asset_obj.user.username,
                           "password": decrypt_p(asset_obj.user.password),
                           "private_key": asset_obj.user.private_key.name
                           }]
                # ansbile_asset_hardware.delay(ids, assets)

        except Exception as e:
            logger.error(e)
            ret['status'] = False
            ret['error'] = '获取资产信息错误{}'.format(e)
        finally:
            return HttpResponse(json.dumps(ret))




@login_required
def AssetZtree(request):
    """
    获取 区域 资产树 的相关数据
    :param request:
    :return:
    """

    manager = AssetInfo.objects.values("project").distinct()
    data = [{"id": "1111", "pId": "0", "name": "项目"}, ]
    for i in manager:
        data.append({"id": i['project'], "pId": "1111",
                     "name": i['project'], "page": "xx.action"}, )
    return HttpResponse(json.dumps(data), content_type='application/json')


class AssetUserListAll(LoginRequiredMixin, ListView):
    """
    登录用户列表
    """
    template_name = 'asset/asset-user.html'
    paginate_by = settings.DISPLAY_PER_PAGE
    model = AssetLoginUser
    context_object_name = "asset_user_list"
    queryset = AssetLoginUser.objects.all()
    ordering = ('id',)

    def get_context_data(self, **kwargs):
        context = {
            "asset_active": "active",
            "asset_user_list_active": "active",

        }
        kwargs.update(context)

        return super().get_context_data(**kwargs)


class AssetUserAdd(LoginRequiredMixin, CreateView):
    """
    登录用户增加
    """
    model = AssetLoginUser
    form_class = AssetUserForm
    template_name = 'asset/asset-user-add-update.html'
    success_url = reverse_lazy('asset:asset_user_list')

    def get_context_data(self, **kwargs):
        context = {
            "asset_active": "active",
            "asset_user_list_active": "active",
        }
        kwargs.update(context)
        print(super().get_context_data(**kwargs))
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        forms = form.save()
        password_form = form.cleaned_data['password']
        if password_form is not None:
            password = encrypt_p(password_form)
            forms.password = password
            forms.save()

        name = form.cleaned_data['hostname']
        obj = AssetLoginUser.objects.get(hostname=name).private_key.name
        system("chmod  600  {0}".format(obj))
        return super().form_valid(form)


class AssetUserUpdate(LoginRequiredMixin, UpdateView):
    """登录用户更新"""

    model = AssetLoginUser
    form_class = AssetUserForm
    template_name = 'asset/asset-user-add-update.html'
    success_url = reverse_lazy('asset:asset_user_list')

    def get_context_data(self, **kwargs):
        context = {
            "asset_active": "active",
            "asset_user_list_active": "active",
        }
        kwargs.update(context)
        print(super().get_context_data(**kwargs))
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        pk = self.kwargs.get(self.pk_url_kwarg, None)
        obj = AssetLoginUser.objects.get(id=pk)

        old_password = obj.password
        new_password = form.cleaned_data['password']
        forms = form.save()

        if new_password is None:
            forms.password = old_password
        else:
            password = encrypt_p(new_password)
            forms.password = password

        forms.save()
        name = form.cleaned_data['hostname']
        obj = AssetLoginUser.objects.get(hostname=name).private_key.name
        system("chmod  600  {0}".format(obj))


        return super().form_valid(form)


class AssetUserDetail(LoginRequiredMixin, DetailView):
    """
    登录用户详细
    """
    model = AssetLoginUser
    template_name = 'asset/asset-user-detail.html'

    def get_context_data(self, **kwargs):
        pk = self.kwargs.get(self.pk_url_kwarg, None)
        detail = AssetLoginUser.objects.get(id=pk)

        context = {
            "asset_active": "active",
            "asset_user_list_active": "active",
            "assets": detail,
            "nid": pk,
        }
        kwargs.update(context)

templates/asset/asset-add-update.html
{% extends "base.html" %}
{% block  title %}资产增改{% endblock %}
{% block header-css %}
    {% load bootstrap3 %}
{% endblock %}


{% block page-content %}

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>资产增改</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index">主页</a>
                </li>
                <li>
                    <a href="{% url    'asset:asset_list' %}">资产管理</a>
                </li>
                <li class="active">
                    <strong>资产增改</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>


    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>资产增改</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">选项 1</a>
                            </li>
                            <li><a href="#">选项 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">

                    <form enctype="multipart/form-data" method="post" class="form-horizontal" action="">
                        {% csrf_token %}
                        {% if form.non_field_errors %}
                            <div class="alert alert-danger" style="margin: 20px auto 0px">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}

                        <div class="form-group">
                            <div class="col-sm-10 col-sm-offset-0">
                                <h3>基本</h3>
                                {% bootstrap_field form.hostname layout="horizontal" %}
                                {% bootstrap_field form.network_ip layout="horizontal" %}
                                {% bootstrap_field form.inner_ip layout="horizontal" %}
                                {% bootstrap_field form.platform layout="horizontal" %}
                                {% bootstrap_field form.region layout="horizontal" %}
                                {% bootstrap_field form.manager layout="horizontal" %}
                                  {% bootstrap_field form.project layout="horizontal" %}

                                {% bootstrap_field form.user layout="horizontal" %}
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>


                        <div class="form-group">
                            <div class="col-sm-10 col-sm-offset-0">
                                <h3>可自动获取</h3>
                                {% bootstrap_field form.system layout="horizontal" %}
                                {% bootstrap_field form.cpu layout="horizontal" %}
                                {% bootstrap_field form.memory layout="horizontal" %}
                                {% bootstrap_field form.disk layout="horizontal" %}
                            </div>
                        </div>


                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <div class="col-sm-10">
                                <input type="hidden" name="__next__" value="{{ i__next__ }}">
                                <h3>其他</h3>
                                {% bootstrap_field form.bandwidth layout="horizontal" %}
                                {% bootstrap_field form.port layout="horizontal" %}

                                {% bootstrap_field form.ps layout="horizontal" %}
                                {% bootstrap_field form.is_active layout="horizontal" %}


                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>


                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-3">

                                {% bootstrap_button "保存" button_type="submit" button_class="btn-primary" %}
                                 <!--<input type="submit" name="__next__" value="submit">-->
                                  <a class="btn btn-white" href="{{ i__next__ }}">取消</a>

                            </div>
                        </div>

                    </form>


                </div>
            </div>
        </div>

    </div>


    {% block footer-js %}
        <script>
            $(document).ready(function () {
                $('.select2').select2();
                $("#id_tags").select2({
                    tags: true,

                    closeOnSelect: false
                });
            });




        </script>
    {% endblock %}



{% endblock %}

templates/asset/asset-user-asset.html
{% extends "base.html" %}
{% block  title %}登录用户{% endblock %}
{% block header-css %}

    {% load bootstrap3 %}
{% endblock %}


{% block  page-content %}

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>关联资产</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a href="asset-user.html">登录用户</a>
                </li>
                <li class="active">
                    <strong>关联资产</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="panel-options">
                        <ul class="nav nav-tabs">

                            <li>
                                <a href="{% url  "asset:asset_user_detail"  pk=nid %}" class="text-center"><i
                                        class="fa fa-laptop"></i>登录用户</a>
                            </li>
                            <li class="active">

                                <a class="text-center" href="{% url  "asset:asset_user_asset"   pk=nid %}"><i
                                        class="fa fa-laptop"></i>关联资产</a>
                            </li>


                            <li class="pull-right">
                                <a class="btn btn-outline btn-default"
                                   href="{% url "asset:asset_user_update"  nid %}"><i
                                        class="fa fa-edit"></i>编辑</a>
                            </li>
                            <li class="pull-right">
                                <a class="btn btn-outline btn-danger  asset_user_del">
                                    <i class="fa fa-edit"></i>删除
                                </a>
                            </li>

                        </ul>
                    </div>
                    <div class="ibox-title">
                        <h5>关联资产</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">选项 1</a>
                                </li>
                                <li><a href="#">选项 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover dataTables-example">
                                <thead>
                                <tr>

                                    <th>主机名</th>
                                    <th>外网IP</th>
                                    <th>内网IP</th>
                                    <th>平台</th>
                                    <th>负责人</th>
                                    <th>项目</th>
                                    <th>动作</th>

                                </tr>
                                </thead>
                                <tbody>

                                {% for   row   in   assets_list %}
                                    <tr class="gradeA" id="{{ row.id }}">

                                        <td class="center"><a
                                                href="{% url  "asset:asset_detail"   pk=row.id %}">{{ row.hostname }}</a>
                                        </td>
                                        <td class="center">{{ row.network_ip }}</td>
                                        <td class="center">{{ row.inner_ip }}</td>
                                        <td class="center">{{ row.platform }} -- {{ row.region }}</td>
                                        <td class="center">{{ row.manager }}</td>
                                        <td class="center">{{ row.project }}</td>
                                        <td><a class="btn btn-primary  btn-xs "
                                               href="{% url  "asset:asset_update"  pk=row.id %}">编辑</a>
                                            <a class="btn btn-danger  btn-xs  asset_del"
                                            >删除</a></td>

                                    </tr>
                                {% endfor %}

                                </tbody>
                                <tfoot>
                                <tr>

                                    <th>主机名</th>
                                    <th>外网IP</th>
                                    <th>内网IP</th>
                                    <th>平台</th>
                                    <th>负责人</th>
                                    <th>项目</th>
                                    <th>动作</th>

                                </tr>
                                </tfoot>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>




    {% block footer-js %}


        <script>


            $(function () {

                 $(document).on('click', '.asset_del', function () {
                    var id = $(this).parent().parent().attr('id');
                    swal({
                        title: "你确定删除",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",
                        closeOnConfirm: false
                    }, function () {
                        $.ajax({
                            headers: {"X-CSRFToken": '{{ csrf_token }}'},
                            url: "/asset/asset-all-del.html",
                            type: 'POST',
                            data: {'nid': id},
                            success: function (data) {
                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        window.location.reload();
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }
                        });


                    });

                });



                $('.asset_user_del').click(function () {
                    swal({

                        title: "你确定删除",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",
                        closeOnConfirm: false
                    }, function () {
                        $.ajax({
                            url: "/asset/asset-user-all-del.html",
                            type: 'POST',
                            data: {'nid': {{  nid }}},
                            success: function (data) {

                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        location.href = "{% url "asset:asset_list" %}"
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }
                        });


                    });
                });


            });


        </script>


    {% endblock %}


{% endblock %}