asset/urls.py
from django.urls import path
from asset import views
from asset import api

urlpatterns = [
    path('asset.html', views.AssetListAll.as_view(), name='asset_list'),
    path('asset-add.html', views.AssetAdd.as_view(), name='asset_add'),
    path('asset-all-del.html', views.AssetAllDel.as_view(), name='asset_all_del'),
    path('asset-detail-<int:pk>.html', views.AssetDetail.as_view(), name='asset_detail'),
    path('asset-update-<int:pk>.html', views.AssetUpdate.as_view(), name='asset_update'),

    path('asset-ztree.html', views.AssetZtree, name='asset_ztree'),

    path('api/asset.html', api.AssetList.as_view(), name='asset_api_list'),
    path('api/asset-detail-<int:pk>.html', api.AssetDetail.as_view(), name='asset_api_detail'),

    path('asset-user.html', views.AssetUserListAll.as_view(), name='asset_user_list'),
    path('asset-user-add.html', views.AssetUserAdd.as_view(), name='asset_user_add'),
    path('asset-user-all-del.html', views.AssetUserAllDel.as_view(), name='asset_user_all_del'),
    path('asset-user-detail-<int:pk>.html', views.AssetUserDetail.as_view(), name='asset_user_detail'),
    path('asset-user-update-<int:pk>.html', views.AssetUserUpdate.as_view(), name='asset_user_update'),

    path('asset-user-asset-<int:pk>.html', views.AssetUserAsset, name='asset_user_asset'),

    path('asset-webssh.html', views.AssetWeb.as_view(), name='asset_web'),
    path('asset-hardware-update.html', views.AssetHardwareUpdate.as_view(), name='asset_hardware_update'),
]

app_name = "asset"

chain/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from index.views import index, login_view, logout, password_update, login_historys

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('', index),
    path('index', index, name="index"),
    path('login', login_view),
    path('logout', logout),
    path('password_update', password_update, name="password_update"),
    path('index/login-history', login_historys, name="login-history"),
    path('asset/', include('asset.urls', namespace="asset", ), ),
    # path('tasks/', include('tasks.urls', namespace="tasks", ), ),
]

templates/_css.html
{% load  static %}

<link href=" {% static  "css/bootstrap.min.css" %}" rel="stylesheet">
<link href="{% static  "font-awesome/css/font-awesome.css" %}" rel="stylesheet">

<link href="{% static  "css/animate.css" %}" rel="stylesheet">
<link href="{% static "css/style.css"  %} " rel="stylesheet">

<link href="{% static "css/datatables.min.css"%} "   rel="stylesheet">

<link href="{% static "css/plugins/select2/select2.min.css"%} "   rel="stylesheet">



<link href="{% static  "css/plugins/sweetalert/sweetalert.css"%}" rel="stylesheet">

<link href="{% static "css/animate.css"%}" rel="stylesheet">
<link href="{% static "css/style.css"%}" rel="stylesheet">


<!-- Toastr style -->
<link  href="{% static  "css/plugins/toastr/toastr.min.css" %}"  rel="stylesheet">

templates/_footer.html
  <div class="footer">
            <div class="pull-right">
               <strong>Version XXXX</strong>
            </div>
            <div>
                <strong>XXXXX</strong> Company &copy; 2018-0713
            </div>
        </div>

templates/_js.html
{% load  static %}

<script src="{% static  "js/jquery-3.1.1.min.js"%}"></script>
<script src="{% static  "js/bootstrap.min.js"%}"></script>
<script src="{% static  "js/plugins/metisMenu/jquery.metisMenu.js"%}"></script>
<script src="{% static  "js/plugins/slimscroll/jquery.slimscroll.min.js"%}"></script>

<!-- Custom and plugin javascript -->
<script src="{% static  "js/inspinia.js"%} "></script>
<script src="{% static  "js/plugins/pace/pace.min.js"%}"></script>


<script src="{% static  "js/datatables.min.js" %}"></script>


<script src="{% static  "js/plugins/select2/select2.full.min.js" %}"></script>


<!-- Sweet alert -->
<script src="{% static  "js/plugins/sweetalert/sweetalert.min.js" %}"></script>

 <!-- Toastr script -->
<script src="{% static  "js/plugins/toastr/toastr.min.js"%}"></script>

<script type="text/javascript" src="{% static 'js/plugins/ztree/jquery.ztree.all.min.js' %}"></script>



<!-- Page-Level Scripts -->
<script>
   $(document).ready(function () {



         $('.dataTables-example').DataTable({

            "oLanguage": {
                "sLengthMenu": "每页显示 _MENU_ 条记录",
                "sZeroRecords": "对不起，查询不到任何相关数据",
                "sInfo": "当前显示 _START_ 到 _END_ 条，共 _TOTAL_条记录",
                "sInfoEmtpy": "找不到相关数据",
                "sInfoFiltered": " 数据表中共为 _MAX_ 条记录",
                "sProcessing": "正在加载中...",
                "sSearch": "搜索",
                "oPaginate": {
                    "sFirst": "第一页",
                    "sPrevious": " 上一页 ",
                    "sNext": " 下一页 ",
                    "sLast": " 最后一页 "
                }
            },
            "order": [[1, 'desc']],
            destroy:true,
            columnDefs: [{
                'targets': [0],    //都默认不排序
                'orderable': false
            }],


            dom: '<"html5buttons"B>lTfgitp,',

            buttons: [],
            lengthMenu: [[15, 40, 70, -1], [15, 40, 70, "全部"]]
        });

    });


   $("#CheckedAll").click(function () {
        if ($(this).is(":checked")) {
            $("[name=id]:checkbox").prop("checked", true);
        } else {
            $("[name=id]:checkbox").prop("checked", false);
        }
    });

    </script>

templates/_nav.html
<nav class="navbar-default navbar-static-side  " role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong
                                    class="font-bold">{{ user }}</strong>

                             </span> <span class="text-muted text-xs block">
                                {% ifequal  user.is_superuser  1 %}
                                    管理员 {% else %} 普通用户 {% endifequal %}
                                <b class="caret"></b></span> </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="{% url  "password_update" %}">修改密码</a></li>
                        <li><a href="/logout.html">登出</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    Chain
                </div>
            </li>
            <li>
                <a href="{% url "index" %}"><i class="fa fa-th-list"></i> <span class="nav-label">首页</span>
                </a>

            </li>
            <li class="{{ asset_active }}">
                <a href="#"><i class="fa fa-inbox"></i> <span class="nav-label">资产管理</span>
                    <span class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li class="{{ asset_list_active }}"><a href="{% url    'asset:asset_list' %}">资产信息</a></li>
                    <li class="{{ asset_user_list_active }}"><a href="{% url    'asset:asset_user_list' %}">登录用户</a>
                    </li>



                </ul>
            </li>


            <li class="{{ index_active }}">
                <a href="#"><i class="fa fa-gears"></i> <span class="nav-label">后台</span>
                    <span class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li class="{{ index_login_active }}"><a href="{% url  'login-history' %}">登录历史</a></li>
                    <li><a href="/admin" target="_blank">管理界面</a></li>

                </ul>
            </li>

        </ul>

    </div>
</nav>

templates/_navbar-static-top.html
<div class="row border-bottom">
            <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
{#                    <form role="search" class="navbar-form-custom" method="post" action="#">#}
{#                        <div class="form-group">#}
{#                            <input type="text" placeholder="请输入搜索内容" class="form-control" name="top-search" id="top-search">#}
{#                        </div>#}
{#                    </form>#}
                </div>
                <ul class="nav navbar-top-links navbar-right">
                    欢迎 {{ user  }} 使用   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                    <li>
                        <a href="/logout.html">
                            <i class="fa fa-sign-out"></i> 注销
                        </a>
                    </li>
                </ul>

            </nav>
        </div>

templates/base.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block  title %}{% endblock %}</title>

    {% include  "_css.html" %}
    {% block header-css %}
    {% endblock %}


</head>

<body>
<div id="wrapper" class="container1">


    {% include "_nav.html" %}

    <div id="page-wrapper" class="gray-bg">
        {% include  "_navbar-static-top.html" %}

        {% block page-content %}


        {% endblock %}
        {% include  "_footer.html" %}

    </div>
</div>


<div id="terminal"></div>

{% include  "_js.html" %}
{% block footer-js %}

{% endblock %}

{% block footer-js-ajax %}
    <script type="text/JavaScript">
        $.ajaxSetup({headers: {"X-CSRFToken": '{{ csrf_token }}'}});
    </script>
{% endblock %}
</body>

</html>